scrollback_lines 10000
map ctrl+shift+f11 toggle_fullscreen
close_on_child_death no

# BEGIN_KITTY_FONTS
font_family      family="Adwaita Mono"
symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14
# END_KITTY_FONTS

adjust_line_height 15
adjust_column_width 1
modify_font underline_position 2
modify_font strikethrough_position 6px
window_padding_width 0 2
background #323232
term xterm-256color
allow_remote_control yes
shell zsh
startup_session launch.conf
env TERM_EMULATOR=kitty
